packages:
  - "apps/*"
  - "packages/*"

catalog:
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
  react19:
    react: 19.1.0
    react-dom: 19.1.0
  trpc:
    "@trpc/client": 11.1.1
    "@trpc/react-query": 11.1.1
    "@trpc/server": 11.1.1