packages:
  - apps/*
  - packages/*
catalogs:
  react-rn:
    react: 19.0.0
    react-dom: 19.0.0
  react19:
    react: 19.0.0
    react-dom: 19.0.0
  trpc:
    "@trpc/client": 11.1.1
    "@trpc/react-query": 11.1.1
    "@trpc/server": 11.1.1
  orpc:
    "@orpc/client": 1.9.0
    "@orpc/tanstack-query": 1.9.0
    "@orpc/server": 1.9.0
catalog:
  "@babel/core": ^7.25.2
  "@expo/vector-icons": ^14.0.2
  "@iconify-json/devicon-plain": ^1.2.4
  "@iconify-json/logos": ^1.2.3
  "@iconify-json/lucide": ^1.2.8
  "@iconify-json/simple-icons": ^1.2.7
  "@prisma/client": 5.20.0
  "@radix-ui/react-checkbox": ^1.1.2
  "@radix-ui/react-dialog": ^1.1.2
  "@radix-ui/react-icons": ^1.3.0
  "@radix-ui/react-label": ^2.1.0
  "@radix-ui/react-popover": ^1.1.2
  "@radix-ui/react-scroll-area": ^1.2.0
  "@radix-ui/react-select": ^2.1.2
  "@radix-ui/react-separator": ^1.1.0
  "@radix-ui/react-slot": ^1.1.0
  "@radix-ui/react-tabs": ^1.1.1
  "@react-navigation/bottom-tabs": ^7.0.0
  "@react-navigation/native": ^7.0.0
  "@tanstack/react-query": ^5.59.13
  "@types/jest": ^29.5.12
  "@types/react-test-renderer": ^18.3.0
  "@typeschema/valibot": ^0.14.0
  "@typescript-eslint/eslint-plugin": ^8.8.1
  "@typescript-eslint/parser": ^8.8.1
  "@unocss/postcss": 66.1.0-beta.2
  "@vitejs/plugin-react": ^4.3.4
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  consola: ^3.2.3
  dotenv: ^16.5.0
  eslint-config-hyoban: ^4.0.3
  eslint-config-next: 15.1.7
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-react-refresh: ^0.4.12
  expo: ~52.0.6
  expo-blur: ~14.0.1
  expo-constants: ~17.0.3
  expo-font: ~13.0.1
  expo-haptics: ~14.0.0
  expo-linking: ~7.0.2
  expo-router: ~4.0.5
  expo-splash-screen: ~0.29.9
  expo-status-bar: ~2.0.0
  expo-symbols: ~0.2.0
  expo-system-ui: ~4.0.2
  expo-web-browser: ~14.0.1
  fastify: ^5.0.0
  framer-motion: ^11.11.8
  jest: ^29.2.1
  jest-expo: ~52.0.1
  nativewind: ^4.1.23
  next: 15.3.1
  next-themes: ^0.3.0
  prettier: ^3.2.5
  prisma: ^5.20.0
  react-native: 0.76.1
  react-native-gesture-handler: ~2.20.2
  react-native-reanimated: ~3.16.1
  react-native-safe-area-context: 4.12.0
  react-native-screens: ~4.0.0
  react-native-web: ~0.19.13
  react-native-webview: 13.12.2
  react-router: 7.6.3
  react-router-dom: 7.6.3
  react-test-renderer: 18.3.1
  rimraf: ^6.0.1
  sonner: ^1.5.0
  tailwind-merge: ^2.5.3
  tailwindcss: ^3.4.14
  tsx: ^4.19.4
  turbo: ^2.5.0
  unocss: ^66.1.0
  unocss-preset-animations: ^1.1.1
  unocss-preset-shadcn: ^0.3.2
  unplugin-auto-import: ^19.1.0
  unplugin-icons: ^22.1.0
  valibot: ^1.0.0
  vite-plugin-checker: ^0.10.3
  vite-plugin-pages: ^0.33.0
  vitest: ^2.1.8
  zod: ^3.23.8
