name: CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/**/*'
      - 'packages/**/*'
  pull_request:
    branches: [ main, develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.5.2
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run build
