name: CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/**/*'
      - 'packages/**/*'
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
      - run: vp install
      - run: vp run check
      - run: vp run build
